######################################################################
# Automatically generated by qmake (2.01a) Mon May 5 15:50:08 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
